import styles from './index.module.css';
import { type NextPage } from 'next';
import Head from 'next/head';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { useState } from 'react';

const Home: NextPage = () => {
  const [isCorrect, setIsCorrect] = useState(false);
  const handleClick = (correctAnswer: boolean) => {
    if (correctAnswer) {
      setIsCorrect(true);
      toast.dismiss();
    } else {
      toast.error(`You are not my love!`);
    }
  };
  return (
    <>
      <Head>
        <title>Mission love</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <ToastContainer />;
        {!isCorrect ? (
          <div className={styles.container}>
            <h1 className={styles.title}>
              Welcome <span className={styles.pinkSpan}>Adventurer</span>
            </h1>
            <p className={styles.question}>
              Please click on the correct SQL query!
            </p>
            <div>
              <p onClick={() => handleClick(false)} className={styles.answer}>
                SELECT all FROM customers
              </p>
              <p onClick={() => handleClick(true)} className={styles.answer}>
                SELECT * FROM customers
              </p>
              <p onClick={() => handleClick(false)} className={styles.answer}>
                GET all FROM customers
              </p>
            </div>
          </div>
        ) : (
          <div className={styles.container}>
            <h1 className={styles.title}>
              Now that I know its <span className={styles.pinkSpan}>YOU</span>
            </h1>
            <p className={styles.text}>
              Здравей, смотан! Ти премина изпитанието си успешно!{' '}
              <p>
                Знаеш, че в момента сме изправени пред изпитание и то голямо.
                Винаги сме били заедно и сме се подкрепяли, но с времето се
                приехме за даденост и спряхме да се борим един за друг. Всеки
                живее живота си с надеждата, че нещо ще се промени, но не
                променя нищо. Събирах дълго време смелост за да направя тази
                стъпка, за да променя нещо. Това ми се виждаше единственият
                начин да се &quot;събудим&quot;, трябваше да е нещо голямо!
              </p>
              <p className={styles.pinkSpan} style={{ fontSize: '1.8rem' }}>
                Но, аз те обичам и искам теб!
              </p>
              <p>
                Ако и ти си готова за промяна и искаш да фикснем бъговете и да
                оправим продъкшъна на нашата връзка, те каня на първа среща.
              </p>
              <p style={{ marginTop: '5rem' }}>
                Четвъртък(06/04), 19:15 часа излез пред нас, ще те чакам. Бъди
                облечена със спортен клин и спортна горница, в раница си вземи и
                едни дънки с блуза. Ще си заета следващите няколко часа не си
                планирай друго.
              </p>
              <hr />
              <p>
                Ако решиш, че не желаеш да продължим приключението заедно, аз ще
                уважа решението ти и ще се отдръпна, за да не правя живота ти
                по-труден. Винаги ще можеш да разчиташ на мен за всичко!
              </p>
            </p>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
